# topics to be covered 
* introduction
* pandas data  structure
* seireis crud operations
* series using list dictionary and nd array
* series indexing 
* series methods

In [1]:
import pandas as pd
pd.__version__

'3.0.5'

In [2]:
s=pd.Series([1,2,3,4,5],name='my_series')
s

0    1
1    2
2    3
3    4
4    5
Name: my_series, dtype: int64

In [3]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'],name='my_series')
s

a    1
b    2
c    3
d    4
e    5
Name: my_series, dtype: int64

In [5]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [7]:
nan_ex= pd.Series([1,2,3,4,none])
print(nan_ex.count())

NameError: name 'none' is not defined

In [10]:
s1=pd.read_csv("C:\\Users\\Addya Swaroop\\python dv\\stores.csv")
print(type(s1))

<class 'pandas.DataFrame'>

In [11]:
print(s1)

   StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
17    STR118      Apparel Zone       Apparel   Mumbai           32.4
18    STR119       Super Bazar  Super Market   Mumbai           30.4
19    STR120      Super Market  Super Market   Mumbai           33.9
20    STR121     Central Store  Super Market   Mumbai           21.5
21    STR122      Apparel Zone       Apparel   Mumbai           15.5
22    STR123     Fashion Bazar       Apparel   Mumbai           15.2
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
25    STR126      Apparel Zone       Apparel  Kolkata           27.3
26    STR127       Super Bazar  Super Market  Kolkata           26.0
27    STR128      Super Market  Super Market  Kolkata           30.4
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0
31    STR132     Digital Bazar  Electronincs  Kolkata           21.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
17         40        78.7               66            4.08       2.200
18         40        75.7               52            4.93       1.615
19         40        71.1               65            4.22       1.835
20         40       120.1               97            3.70       2.465
21         80       318.0              150            2.76       3.520
22         80       304.0              150            3.15       3.435
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
25         40        79.0               66            4.08       1.935
26         40       120.3               91            4.43       2.140
27         40        95.1              113            3.77       1.513
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570
31         40       121.0              109            4.11       2.780

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
17          19.47         1               1       4             1
18          18.52         1               1       4             2
19          19.90         1               1       4             1
20          20.01         1               0       3             1
21          16.87         0               0       3             2
22          17.30         0               0       3             2
23          15.41         0               0       3             4
24          17.05         0               0       3             2
25          18.90         1               1       4             1
26          16.70         0               1       5             2
27          16.90         1               1       5             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4
31          18.60         1               1       4             2

In [12]:
print(s1.head())

  StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0
1    STR102      Apparel Zone       Apparel    Delhi           21.0
2    STR103       Super Bazar  Super Market    Delhi           22.8
3    STR104      Super Market  Super Market    Delhi           21.4
4    STR105     Central Store  Super Market    Delhi           18.7

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620
1         60       160.0              110            3.90       2.875
2         40       108.0               93            3.85       2.320
3         60       258.0              110            3.08       3.215
4         80       360.0              175            3.15       3.440

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0          16.46         0               1       4             4
1          17.02         0               1       4             4
2          18.61         1               1       4             1
3          19.44         1               0       3             1
4          17.02         0               0       3             2

In [14]:
s1.head(20)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2
5,STR106,Apparel Zone,Apparel,Delhi,18.1,60,225.0,105,2.76,3.460,20.22,1,0,3,1
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4
7,STR108,Digital Bazar,Electronincs,Delhi,24.4,40,146.7,62,3.69,3.190,20.00,1,0,4,2
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.440,18.90,1,0,4,4
11,STR112,Super Market,Super Market,Chennai,16.4,80,275.8,180,NaN,4.070,17.40,0,0,3,3
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4
16,STR117,Electronics Zone,Electronincs,Mumbai,14.7,80,440.0,230,3.23,5.345,17.42,0,0,3,4
17,STR118,Apparel Zone,Apparel,Mumbai,32.4,40,78.7,66,4.08,2.200,19.47,1,1,4,1
18,STR119,Super Bazar,Super Market,Mumbai,30.4,40,75.7,52,4.93,1.615,18.52,1,1,4,2
19,STR120,Super Market,Super Market,Mumbai,33.9,40,71.1,65,4.22,1.835,19.90,1,1,4,1

In [15]:
s1.tail()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.9,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.5,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.5,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.6,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.6,1,1,4,2

In [16]:
s1.tail(20)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4
16,STR117,Electronics Zone,Electronincs,Mumbai,14.7,80,440.0,230,3.23,5.345,17.42,0,0,3,4
17,STR118,Apparel Zone,Apparel,Mumbai,32.4,40,78.7,66,4.08,2.200,19.47,1,1,4,1
18,STR119,Super Bazar,Super Market,Mumbai,30.4,40,75.7,52,4.93,1.615,18.52,1,1,4,2
19,STR120,Super Market,Super Market,Mumbai,33.9,40,71.1,65,4.22,1.835,19.90,1,1,4,1
20,STR121,Central Store,Super Market,Mumbai,21.5,40,120.1,97,3.70,2.465,20.01,1,0,3,1
21,STR122,Apparel Zone,Apparel,Mumbai,15.5,80,318.0,150,2.76,3.520,16.87,0,0,3,2
22,STR123,Fashion Bazar,Apparel,Mumbai,15.2,80,304.0,150,3.15,3.435,17.30,0,0,3,2
23,STR124,Digital Bazar,Electronincs,Mumbai,13.3,80,350.0,245,3.73,3.840,15.41,0,0,3,4
24,STR125,Electronics Zone,Electronincs,Kolkata,19.2,80,400.0,175,3.08,3.845,17.05,0,0,3,2
25,STR126,Apparel Zone,Apparel,Kolkata,27.3,40,79.0,66,4.08,1.935,18.90,1,1,4,1
26,STR127,Super Bazar,Super Market,Kolkata,26.0,40,120.3,91,4.43,2.140,16.70,0,1,5,2
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.90,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.50,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.50,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.60,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.60,1,1,4,2

In [17]:
s1.describe()

,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
count,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,20.090625,61.875000,230.721875,146.687500,3.651034,3.217250,17.848750,0.437500,0.406250,3.687500,2.625000
std,6.026948,17.859216,123.938694,68.562868,0.532664,0.978457,1.786943,0.504016,0.498991,0.737804,1.211504
min,10.400000,40.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.000000
25%,15.425000,40.000000,120.825000,96.500000,3.150000,2.581250,16.892500,0.000000,0.000000,3.000000,2.000000
50%,19.200000,60.000000,196.300000,123.000000,3.730000,3.325000,17.710000,0.000000,0.000000,4.000000,2.000000
75%,22.800000,80.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.000000
max,33.900000,80.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,4.000000

In [18]:
print(s1.info())

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StoreCode        32 non-null     str
 1   StoreName        32 non-null     str
 2   StoreType        32 non-null     str
 3   Location         32 non-null     str
 4   OperatingCost    32 non-null     float64
 5   Staff_Cnt        32 non-null     int64
 6   TotalSales       32 non-null     float64
 7   Total_Customers  32 non-null     int64
 8   AcqCostPercust   29 non-null     float64
 9   BasketSize       32 non-null     float64
 10  ProfitPercust    32 non-null     float64
 11  OwnStore         32 non-null     int64
 12  OnlinePresence   32 non-null     int64
 13  Tenure           32 non-null     int64
 14  StoreSegment     32 non-null     int64
dtypes: float64(5), int64(6), str(4)
memory usage: 3.9 KB
None